### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by s-a-n-a-n-t** [glimpseio/GlimpseXML#3]
Hi thanks for creating GlimpseXML!! We think we have discovered a memory leak in Node class. When the code returns the text property it does not run xmlFree or deallocate the string returned by a call to xmlNodeGetContent. This causes a leak each time an xml node's text property is accessed. It also shows up in Instruments. Any help appreciated!

Thanks again,
S-a-n-a-n-t

**Comment by marcprux** [comment]
Fixed. Thanks for reporting it.

**Comment by s-a-n-a-n-t** [comment]
Most welcome! Thanks for quick turnaround.

**Comment by s-a-n-a-n-t** [comment]
Can this change also be done on master branch? We are using swift 1.2 and cannot switch to using the swift2 branch.

Thanks much
